Repository wecode-bootcamp-korea/24-2nd-FX-backend, pull requests merged in 2021-09, with the labels that each got.

#1 [FX-BE]
  config/settings.py
  contents/__init__.py
  contents/admin.py
  contents/apps.py
  contents/migrations/0001_initial.py
  contents/migrations/0002_auto_20210914_1924.py
  contents/migrations/__init__.py
  contents/models.py
  contents/tests.py
  contents/views.py
  core/__init__.py
  core/admin.py
  core/apps.py
  core/migrations/__init__.py
  core/models.py
  core/tests.py
  core/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/0002_alter_user_email.py
  users/migrations/0003_auto_20210914_1924.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
  wishlists/__init__.py
  wishlists/admin.py
  wishlists/apps.py
  wishlists/migrations/0001_initial.py
  wishlists/migrations/__init__.py
  wishlists/models.py
  wishlists/tests.py
  wishlists/views.py
Labels: Status: 리뷰 요청

#2 [고준영]Add: Create db_uploader.py
  config/settings.py
  contents/migrations/0002_auto_20210914_1924.py
  contents/migrations/0003_alter_detail_running_time.py
  contents/migrations/0004_alter_detail_episode.py
  contents/models.py
  db_uploader.py
Labels: Status: 리뷰 요청

#3 [고준영]Add: Content Detail info endpoint
  config/urls.py
  contents/urls.py
  contents/views.py
Labels: Status: 리뷰 요청

#4 [김장호] Add: added FLIX sign-up view
  config/urls.py
  requirements.txt
  users/migrations/0004_alter_user_kakao_id.py
  users/models.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#5 [고준영]Add: Contents List endpoint
  contents/urls.py
  contents/views.py
Labels: Status: 리뷰 요청

#6 [김장호] Add: added basic login view
  requirements.txt
  users/login_decorator.py
  users/tests.py
  users/tests/__init__.py
  users/tests/test_sigin_in_view.py
  users/tests/test_sign_up_view.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#9 [고준영] Add: Content, ContentList view
  contents/tests.py
  contents/views.py
Labels: Status: 리뷰 요청

#11 [고준영] Modify: content detail endpoint
  contents/views.py
Labels: Status: 리뷰 요청

#12 [고준영] Add: Togglewishlist
  config/urls.py
  users/login_decorator.py
  wishlists/migrations/0002_alter_wishlist_like.py
  wishlists/models.py
  wishlists/tests.py
  wishlists/urls.py
  wishlists/views.py
Labels: Status: 리뷰 요청

#7 [고준영] Add : Content Video endpoint 구현중
  config/settings.py
  contents/urls.py
  contents/views.py
  db_uploader.py
  requirements.txt
Labels: Status: 리뷰 요청

#13 [고준영] Add: Get WishList
  wishlists/tests.py
  wishlists/views.py
Labels: Status: 리뷰 요청

#14 [김장호] Add: added flix signup_type validation
  users/migrations/0005_alter_user_signup_type.py
  users/migrations/0006_alter_user_signup_type.py
  users/models.py
  users/tests/test_sigin_in_view.py
  users/views.py
Labels: Status: 리뷰 요청

#15 [김장호] Add: added google login
  users/tests/test_google_login_view.py
  users/urls.py
  users/views.py
Labels: Status: Conflict 해결 요청

#10 [김장호] Add: kakao login api
  requirements.txt
  users/kakao_api.py
  users/login_decorator.py
  users/tests/test_kakao_login_view.py
  users/urls.py
  users/views.py
Labels: Status: Rebase 요청

#16 [고준영] 데코레이더 기능 활성화
  config/settings.py
  contents/views.py
  users/login_decorator.py
  users/views.py
Labels: Status: 리뷰 요청
